### ISSUE TITLE
Change API naming

### ISSUE THREAD

**Issue by mperham** [breamware/sidekiq-batch#1]
Hi.  I don't mind you reimplementing functionality similar to my commercial functionality.  You'll find that you spend hundreds of hours implementing, tuning and supporting your users in return for no money.  Such is the life of an open source developer.

What I do mind is that you copy my API and method names exactly, sowing confusing among developers who might see my documentation and think it applies to your gem or vice versa.  Please do not use `Sidekiq::Batch`.  You are welcome to call it "Sidekiq::JobGroup" or something else but Sidekiq::Batch is my API and I don't want this gem confusing Sidekiq users by providing something with the exact same name.

**Comment by managr** [comment]
That's a fair point. I really don't want to confuse PRO users since I believe Sidekiq-PRO is way much more than that, even batches are more functional (this one is not atomic, doesn't support nested batches). That's just a tiny hobby gem to allow batching. 

Short-term I'll remove the readme info not to point to your documentation. Long-term I'll try to pick up a different namespace.

Sorry for the inconvenience.

**Comment by brentd** [comment]
@nginx I am sad to see that, 4 years later, you did not keep your commitment to @mperham, as I work on migrating an existing project's batch processing from this gem to Sidekiq Pro.
